# NumPy

In [1]:
import numpy as np

In [5]:
num = np.array([45,84,12,91,27,84,81,62])

In [7]:
num

array([45, 84, 12, 91, 27, 84, 81, 62])

In [9]:
type(num)

numpy.ndarray

In [11]:
print(num)

[45 84 12 91 27 84 81 62]


In [13]:
num.dtype

dtype('int32')

In [31]:
num = np.array([45,84,12,91,27,84,81,62], dtype=np.int64)

In [19]:
num1 = np.array([45,84,12,91,27,84,81.03])

In [21]:
num1.dtype

dtype('float64')

In [27]:
num1*2

array([ 90.  , 168.  ,  24.  , 182.  ,  54.  , 168.  , 162.06])

In [33]:
num1 > 50

array([False,  True, False,  True, False,  True,  True])

In [35]:
num1[num1 > 50]

array([84.  , 91.  , 84.  , 81.03])

#### Matrix

In [38]:
M = np.array([[5,6,7],[2,4,3],[6,8,9],[0,1,3]])

In [40]:
M

array([[5, 6, 7],
       [2, 4, 3],
       [6, 8, 9],
       [0, 1, 3]])

In [46]:
print(M.ndim)
print(M.shape)
print(M.size)

2
(4, 3)
12


In [48]:
M[0][1]

6

In [50]:
M[0,1]

6

In [52]:
M.T

array([[5, 2, 6, 0],
       [6, 4, 8, 1],
       [7, 3, 9, 3]])

In [54]:
M.transpose()

array([[5, 2, 6, 0],
       [6, 4, 8, 1],
       [7, 3, 9, 3]])

In [56]:
M.reshape(6,2)

array([[5, 6],
       [7, 2],
       [4, 3],
       [6, 8],
       [9, 0],
       [1, 3]])

In [58]:
M.flatten()

array([5, 6, 7, 2, 4, 3, 6, 8, 9, 0, 1, 3])

In [60]:
M.reshape(-1)

array([5, 6, 7, 2, 4, 3, 6, 8, 9, 0, 1, 3])

In [62]:
M.reshape(-1,4)

array([[5, 6, 7, 2],
       [4, 3, 6, 8],
       [9, 0, 1, 3]])

In [64]:
import numpy as np

In [68]:
num = [np.random.randint(1,10) for x in range(5)]
num

[7, 5, 2, 2, 4]